# -*- coding: utf-8 -*-
"""Copy of Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYPPy-uHT94rJwWmK4e0jeUNH9W6lMwN
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
  df = pd.read_csv(filename)
  print(f"Successfully loaded '{filename}' into a DataFrame.")
  break

print(df.head())

print(df.columns)

print(df.columns.tolist())
df['Customer_ID'] = (
    df['Customer_Age'].astype(str) + "_" +
    df['Customer_Gender'].astype(str) + "_" +
    df['Country'].astype(str) + "_" +
    df['State'].astype(str)
)
customer_summary = df.groupby('Customer_ID').agg({
    'Revenue':'sum',
    'Profit':'sum',
    'Order_Quantity':'sum'
}).reset_index()

print(customer_summary.head())

frequency = df.groupby('Customer_ID')['Order_Quantity'].count().reset_index()
frequency.rename(columns={'Order_Quantity':'Frequency'}, inplace=True)
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
last_purchase = df.groupby('Customer_ID')['Date'].max().reset_index()
last_purchase['Recency'] = (df['Date'].max() - last_purchase['Date']).dt.days
df['Order_Value'] = df['Revenue']
aov = df.groupby('Customer_ID')['Order_Value'].mean().reset_index()
aov.rename(columns={'Order_Value':'AOV'}, inplace=True)

customer_features = frequency.merge(
    last_purchase[['Customer_ID','Recency']], on='Customer_ID'
)
customer_features = customer_features.merge(aov, on='Customer_ID')
print(customer_features.head())

from xgboost import XGBRegressor

xgb_model = XGBRegressor(n_estimators=100, random_state=42)
xgb_model.fit(X_train, y_train)

xgb_preds = xgb_model.predict(X_test)



!pip install --upgrade scikit-learn

# Commented out IPython magic to ensure Python compatibility.

# %pip install --upgrade scikit-learn

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

print("Random Forest R2:", r2_score(y_test, rf_preds))
print("Random Forest RMSE:", np.sqrt(mean_squared_error(y_test, rf_preds)))

print("XGBoost R2:", r2_score(y_test, xgb_preds))
print("XGBoost RMSE:", np.sqrt(mean_squared_error(y_test, xgb_preds)))

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
rf_mae = mean_absolute_error(y_test, rf_preds)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_preds))
rf_r2 = r2_score(y_test, rf_preds)

print("Random Forest R2:", rf_r2)
print("Random Forest MAE:", rf_mae)
print("Random Forest RMSE:", rf_rmse)
xgb_mae = mean_absolute_error(y_test, xgb_preds)
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_preds))
xgb_r2 = r2_score(y_test, xgb_preds)

print("XGBoost R2:", xgb_r2)
print("XGBoost MAE:", xgb_mae)
print("XGBoost RMSE:", xgb_rmse)

results = X_test.copy()
results['Actual_Revenue'] = y_test.values
results['Predicted_LTV_RF'] = rf_preds
results['Predicted_LTV_XGB'] = xgb_preds

print(results.head())

import pandas as pd
results['Segment'] = pd.qcut(results['Predicted_LTV_RF'],
                             q=3,
                             labels=['Low LTV','Medium LTV','High LTV'])

print(results[['Customer_ID','Predicted_LTV_RF','Segment']].head(10))

results = X_test.copy()
results['Customer_ID'] = customer_features.loc[X_test.index, 'Customer_ID'].values
results['Actual_Revenue'] = y_test.values
results['Predicted_LTV_RF'] = rf_preds
results['Predicted_LTV_XGB'] = xgb_preds

print(results.head())

segment_summary = results.groupby('Segment').agg({
    'Predicted_LTV_RF':'mean',
    'Actual_Revenue':'mean',
    'Customer_ID':'count'
}).rename(columns={'Customer_ID':'Customer_Count'})

print(segment_summary)

import matplotlib.pyplot as plt

results.groupby('Segment')['Predicted_LTV_RF'].mean().plot(kind='bar')
plt.title("Average Predicted LTV by Segment")
plt.ylabel("Predicted LTV")
plt.show()

import matplotlib.pyplot as plt

plt.scatter(results['Actual_Revenue'], results['Predicted_LTV_RF'], alpha=0.6, label="Random Forest")
plt.scatter(results['Actual_Revenue'], results['Predicted_LTV_XGB'], alpha=0.6, label="XGBoost", marker='x')
plt.plot([results['Actual_Revenue'].min(), results['Actual_Revenue'].max()],
         [results['Actual_Revenue'].min(), results['Actual_Revenue'].max()],
         'r--', label="Perfect Fit")
plt.xlabel("Actual Revenue")
plt.ylabel("Predicted LTV")
plt.title("Actual vs Predicted LTV")
plt.legend()
plt.show()

results.boxplot(column='Predicted_LTV_RF', by='Segment')
plt.title("Predicted LTV Distribution by Segment")
plt.suptitle("")
plt.ylabel("Predicted LTV")
plt.show()

results['Segment'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Customer Distribution by LTV Segment")
plt.ylabel("")
plt.show()